# Tarea 6

Eddson Sierra

09/04/2021

In [66]:
# imports
import numpy as np

## np.array vs np.matrix

**Ejercicio**: Investigar y ejemplificar diferencias entre np.array y np.matrix

**Array** permite crear arreglos a partir de listas, secuencias u otros objetos. Es una función más general que **matrix.**

*Argumentos de numpy.array*: numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

En el caso de **matrix** es una función que permite la creación de matrices o arreglos a partir de elementos diferentes como listas y otros objetos. La gran diferencia es que np.matrix solo permite crear matrices de 2D mientras que np.array permite la creación de arreglos N-dimensionales. La función matrix es una subclase de los ndarrays. Se recomienda el uso de np.array en lugar de np.matrix ya que en el futuro esta última será removida.

Ejemplos:

In [3]:
# la gran diferencia es que aunque tanto el arreglo como la matriz se crean con el mismo objeto
# no tienen las mismas dimensiones ni son del mismo tipo:
arr = np.array([1,2,3,4])
mat = np.matrix([1,2,3,4])
arr, mat

(array([1, 2, 3, 4]), matrix([[1, 2, 3, 4]]))

In [4]:
print("Shape del array:", arr.shape, "Shape de la matriz:",mat.shape)

Shape del array: (4,) Shape de la matriz: (1, 4)


In [5]:
print("Type del array:", type(arr), "Type de la matriz:",type(mat))

Type del array: <class 'numpy.ndarray'> Type de la matriz: <class 'numpy.matrix'>


* Ambas tienen un método .T para obtener la matriz traspuesta, pero solo matrix tiene .I (matriz inversa) y .H (Conjugada de la matriz).

In [6]:
arr2 = np.array([[1,2],[3,4]])
print(arr2)
print(arr2.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [7]:
mat2 = np.matrix([[1,2],[3,4]])
print(mat2)
print(mat2.T)
print(mat2.I)
print(mat2.H)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 3]
 [2 4]]


* Ambas pueden ser convertidas entre sí utilizando np.asmatrix() o np.asarray()

In [8]:
matriz_from_arr2 = np.asmatrix(arr2)
matriz_from_arr2

matrix([[1, 2],
        [3, 4]])

In [9]:
arr_from_mat2 = np.asarray(mat2)
arr_from_mat2

array([[1, 2],
       [3, 4]])

## Ejercicio de Valor esperado
**Ejemplo en DS** : en inteligencia artificial y ML en la sub-rama "reinforcement learning" la "ecuacion de bellman" puede aplicarse de manera vectorizada a traves del operar vectores, matrices y escalares en una sola expresión.

<img src="https://rebornhugo.github.io/assets/images/post_images/%E5%BC%BA%E5%8C%96%E5%AD%A6%E4%B9%A02/bellman%20equation2.PNG" width = "400" >

* n = número de estados del sistema.
* V(s) = vector que representa el valor esperado para cierto estado
* R = recompensa inmediata percibida por el agente al salir de cierto estado.(vector)
* P = matriz de transicion de la cadena de Markov sub-yacente.(matriz)
* γ = factor de descuento de recompensas futuras(escalar)

Calcular V(s) para el siguiente sistema aplicando la ecuación de bellman de manera vectorizada.

In [13]:
V = np.array([0,0,0]) # valor inicial de V(s)
R = np.array([10,2,5]) # vector de recompensas
P = np.array([[0.5,0.25,0.25],
              [0.2,0.40,0.40],
              [0.80,0.10,0.10]])  # matriz de transición
gamma = 0.99

In [16]:
V = R + gamma*np.matmul(P,V)
V

array([23.298175, 13.367675, 20.228675])

## Ejercicio de Neural Network

Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png" width="300">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicación de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producirá una nueva matriz con el mismo número de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la función "sigmoid"(descrita a continuación) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamaño pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la función sigmoid. El resultado debe ser un tensor con el mismo número de filas que la matriz X y una sola columna(una predicción para cada fila de X.

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png" width="300">

In [19]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

In [20]:
H1_W = np.array([[0.25,-8],
                 [0.37,14]])
OL_W = np.array([[4],[9]])

X =  np.array([[0.1,0.2],
               [1,2]])

H1 = np.matmul(X,H1_W)
H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1

print(OL)

[[0.99995577]
 [0.99999332]]


In [27]:
def neural_network(X):
    HL = np.matmul(X,H1_W)
    salida = np.matmul(sigmoid(HL),OL_W)
    return sigmoid(salida)

In [28]:
neural_network(X)

array([[0.99995577],
       [0.99999332]])

## Neural Network de 3 neuronas HL y función ReLu 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png" width="300">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png" width="300">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [69]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

In [63]:
def neural_network2(X):  
    HL_M = np.array([[0.712, 0.355, 0.268],[0.112, 0.855, 0.468]]) 
    OUT_M = np.array([[0.116], [0.329], [0.708]])
    HL = np.matmul(X, HL_M)
    salida = np.matmul(sigmoid(HL),OUT_M)
    return sigmoid(salida)

In [64]:
# comprobar que la función es correcta según la imagen
neural_network2(np.array([1,1]))

array([0.69269553])

In [71]:
# crear funcion de activacion ReLu
def ReLu(x):
    return np.log(1+ np.exp(x))

In [72]:
# modificar la funcion de red neuronal
def neural_network2(X):  
    HL_M = np.array([[0.712, 0.355, 0.268],[0.112, 0.855, 0.468]]) 
    OUT_M = np.array([[0.116], [0.329], [0.708]])
    HL = np.matmul(X, HL_M)
    salida = np.matmul(sigmoid(HL),OUT_M)
    return ReLu(salida)

In [73]:
neural_network2(X)

array([[1.21215865],
       [1.08646489],
       [1.42435675],
       [1.42603146],
       [1.41891238],
       [1.12076711],
       [1.42523032],
       [1.42735994],
       [1.42514924],
       [1.42735994]])